project_name: coredns-enum
before:
  hooks:
    - go mod tidy
builds:
  - id: coredns-enum
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w -extldflags='-static'"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
archives:
  - builds:
      - coredns-enum
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
